apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-config-dns
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    integrityshield.io/message: H4sIAAAAAAAAA5VVS0/cMBC+51eMtrcKA31JVYSQgK0qDqCqoB5aocqJJ4uLY1u2k2VV9b934sSw2Q0L+JTMe75vPOZW/kDnpdE5WKNkudo3FjUrVeMDOlZzzRdYow770hy077I7qUUO36JpVmPgggeeZwCa15hisNLoSi6Y0J40XGsTeKAcvjOEFyTygWvBnfA5XJ5fXcPnw0P26cMLnUsecGGcRPI+u4CzWEvjYgVw8WD60mhGB2dUjMXewyn3qKTGcdjMWyy75hz5CRllJ2WIsEpdGVeTTkjPC4UEX8WVxyxlZwFrq6joAR4GpviDZZhjJbWMQaK8O/y1fCXHnrdR0QOJyWKdzHSeJrU/qe10nmwf3sBSKgUFgmnROSkEaihW2x7kAJY76mDIuxbeI/nKsMpBmeVGmd7yEq9QEXDGrdcEgPcEj6BGfs3umgLZ29nNSC/1g15gxRsVRgY9G5sspcOgNKSQXJd4vbIUpSYqbnmLIzPYQeoUuT3YkVx/K6tNOse0zi+vtjRTdK7jRSn6mdnSb5KaTkGjPzc1l1TeUffzW8S/4wlb62RLWP00GqdCBb7wU3KAy1jaEU2N4z64pgyNw/P5MZPDjd1CgBh1GomXeFv7ng4mAiwru/iYg1lqFBljLHv1XRp2n6JB66Sn9Cv1YmILFr2GbV8cm5y/Y7W2NZN0wiNx/JD2e6O60aLqvzrT2Jy+rN9ReeabOHkRcLbzSo+Weyd4TPIsQFuQPlPWBKCxs4k3ZQc6aVaHFLTfhFx7aRjQSxIaWt6za9fgbJigEO9p/xSIsw3Xk5ZL1S3qx7DjtVLzUN5+ubcOvX9M1SX7e4e0m1C30hndVbwHBABtW3KFc70HLVdN9yx1i6ad3fzL/gOMQP4dgAcAAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CSzJUSVJIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9jS01RdjdCWGUxTHVsL1dzZ2N2eG4vUHJqQlZKblpJOWpGMzkxKwpQUVpsR2hEKzBzbDUxZW96eW14L1FqZmhpUVpQU3FFdGIxZ2dFaEc1NEZQZVh4MzJJL0RWOC9vaVhQeVJsZHRwClVWYVFyRmVYejA0ME1Fdnhla25ZZ1NVRkRsNXR5WW5nb1JFa3ArbllVNEVnYU5UU1ZKUmlzZUpKUFIzc3BIM2YKZXdKMHlhWFlEeGtlZXNId3BLZHRQeURMd2dtalo4SDRSd25SZCsrYWNlNWF0Y2l3MGxWdTNqU2pXY3pBTW9WTQptMktPNkRDK2dRK1p4OEtRd28yYnZhL0lvMTErZEFzS3BoK0VsSllKRzluWWxSMXJERzM1aCs3R0szT095c0wvCmFvcGcrc256ZDk2MFZKRlpTYVQ3UTg3aW0xekFWMk93d0FNUTJocHR6Wk1iRmlsMkdXTFRiSU16WWVJa0hOT28KZ3QxK2RwNHpiOXdLQ2hWeFlGNFdLTjc5K3dUREFyZEpmNUxiZ3ZvNHZQV3h0Ulg5cEhIMXJ1SUMveGRlenh1MQpzdkpnNzdOK0h5dmpLTmFuMTRxVUxWWnJ3OE1LMkNYb21kNEdDMmUrV09vMXlPU21nTkZFbjA4b2h5S0gzN0JsCkdNTDJMQ0pENDBWcjUraFg3TG5LSURSOXpCUm9qdTNyCj1mR2Y4Ci0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-config-dns
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: DNS
                metadata:
                  name: cluster
                spec:
                  baseDomain: <base_domain>
                  privateZone:
                  tags:
                    Name: <infrastructureID>-int
                    kubernetes.io/cluster/<infrastructureID>-wfpg4: owned
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-config-dns
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA5VVS0/cMBC+51eMtrcKA31JVYSQgK0qDqCqoB5aocqJJ4uLY1u2k2VV9b934sSw2Q0L+JTMe75vPOZW/kDnpdE5WKNkudo3FjUrVeMDOlZzzRdYow770hy077I7qUUO36JpVmPgggeeZwCa15hisNLoSi6Y0J40XGsTeKAcvjOEFyTygWvBnfA5XJ5fXcPnw0P26cMLnUsecGGcRPI+u4CzWEvjYgVw8WD60mhGB2dUjMXewyn3qKTGcdjMWyy75hz5CRllJ2WIsEpdGVeTTkjPC4UEX8WVxyxlZwFrq6joAR4GpviDZZhjJbWMQaK8O/y1fCXHnrdR0QOJyWKdzHSeJrU/qe10nmwf3sBSKgUFgmnROSkEaihW2x7kAJY76mDIuxbeI/nKsMpBmeVGmd7yEq9QEXDGrdcEgPcEj6BGfs3umgLZ29nNSC/1g15gxRsVRgY9G5sspcOgNKSQXJd4vbIUpSYqbnmLIzPYQeoUuT3YkVx/K6tNOse0zi+vtjRTdK7jRSn6mdnSb5KaTkGjPzc1l1TeUffzW8S/4wlb62RLWP00GqdCBb7wU3KAy1jaEU2N4z64pgyNw/P5MZPDjd1CgBh1GomXeFv7ng4mAiwru/iYg1lqFBljLHv1XRp2n6JB66Sn9Cv1YmILFr2GbV8cm5y/Y7W2NZN0wiNx/JD2e6O60aLqvzrT2Jy+rN9ReeabOHkRcLbzSo+Weyd4TPIsQFuQPlPWBKCxs4k3ZQc6aVaHFLTfhFx7aRjQSxIaWt6za9fgbJigEO9p/xSIsw3Xk5ZL1S3qx7DjtVLzUN5+ubcOvX9M1SX7e4e0m1C30hndVbwHBABtW3KFc70HLVdN9yx1i6ad3fzL/gOMQP4dgAcAAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CSzJUSVJIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9jS01RdjdCWGUxTHVsL1dzZ2N2eG4vUHJqQlZKblpJOWpGMzkxKwpQUVpsR2hEKzBzbDUxZW96eW14L1FqZmhpUVpQU3FFdGIxZ2dFaEc1NEZQZVh4MzJJL0RWOC9vaVhQeVJsZHRwClVWYVFyRmVYejA0ME1Fdnhla25ZZ1NVRkRsNXR5WW5nb1JFa3ArbllVNEVnYU5UU1ZKUmlzZUpKUFIzc3BIM2YKZXdKMHlhWFlEeGtlZXNId3BLZHRQeURMd2dtalo4SDRSd25SZCsrYWNlNWF0Y2l3MGxWdTNqU2pXY3pBTW9WTQptMktPNkRDK2dRK1p4OEtRd28yYnZhL0lvMTErZEFzS3BoK0VsSllKRzluWWxSMXJERzM1aCs3R0szT095c0wvCmFvcGcrc256ZDk2MFZKRlpTYVQ3UTg3aW0xekFWMk93d0FNUTJocHR6Wk1iRmlsMkdXTFRiSU16WWVJa0hOT28KZ3QxK2RwNHpiOXdLQ2hWeFlGNFdLTjc5K3dUREFyZEpmNUxiZ3ZvNHZQV3h0Ulg5cEhIMXJ1SUMveGRlenh1MQpzdkpnNzdOK0h5dmpLTmFuMTRxVUxWWnJ3OE1LMkNYb21kNEdDMmUrV09vMXlPU21nTkZFbjA4b2h5S0gzN0JsCkdNTDJMQ0pENDBWcjUraFg3TG5LSURSOXpCUm9qdTNyCj1mR2Y4Ci0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
placementRef:
  name: placement-policy-config-dns
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-config-dns
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-config-dns
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA5VVS0/cMBC+51eMtrcKA31JVYSQgK0qDqCqoB5aocqJJ4uLY1u2k2VV9b934sSw2Q0L+JTMe75vPOZW/kDnpdE5WKNkudo3FjUrVeMDOlZzzRdYow770hy077I7qUUO36JpVmPgggeeZwCa15hisNLoSi6Y0J40XGsTeKAcvjOEFyTygWvBnfA5XJ5fXcPnw0P26cMLnUsecGGcRPI+u4CzWEvjYgVw8WD60mhGB2dUjMXewyn3qKTGcdjMWyy75hz5CRllJ2WIsEpdGVeTTkjPC4UEX8WVxyxlZwFrq6joAR4GpviDZZhjJbWMQaK8O/y1fCXHnrdR0QOJyWKdzHSeJrU/qe10nmwf3sBSKgUFgmnROSkEaihW2x7kAJY76mDIuxbeI/nKsMpBmeVGmd7yEq9QEXDGrdcEgPcEj6BGfs3umgLZ29nNSC/1g15gxRsVRgY9G5sspcOgNKSQXJd4vbIUpSYqbnmLIzPYQeoUuT3YkVx/K6tNOse0zi+vtjRTdK7jRSn6mdnSb5KaTkGjPzc1l1TeUffzW8S/4wlb62RLWP00GqdCBb7wU3KAy1jaEU2N4z64pgyNw/P5MZPDjd1CgBh1GomXeFv7ng4mAiwru/iYg1lqFBljLHv1XRp2n6JB66Sn9Cv1YmILFr2GbV8cm5y/Y7W2NZN0wiNx/JD2e6O60aLqvzrT2Jy+rN9ReeabOHkRcLbzSo+Weyd4TPIsQFuQPlPWBKCxs4k3ZQc6aVaHFLTfhFx7aRjQSxIaWt6za9fgbJigEO9p/xSIsw3Xk5ZL1S3qx7DjtVLzUN5+ubcOvX9M1SX7e4e0m1C30hndVbwHBABtW3KFc70HLVdN9yx1i6ad3fzL/gOMQP4dgAcAAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CSzJUSVJIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9jS01RdjdCWGUxTHVsL1dzZ2N2eG4vUHJqQlZKblpJOWpGMzkxKwpQUVpsR2hEKzBzbDUxZW96eW14L1FqZmhpUVpQU3FFdGIxZ2dFaEc1NEZQZVh4MzJJL0RWOC9vaVhQeVJsZHRwClVWYVFyRmVYejA0ME1Fdnhla25ZZ1NVRkRsNXR5WW5nb1JFa3ArbllVNEVnYU5UU1ZKUmlzZUpKUFIzc3BIM2YKZXdKMHlhWFlEeGtlZXNId3BLZHRQeURMd2dtalo4SDRSd25SZCsrYWNlNWF0Y2l3MGxWdTNqU2pXY3pBTW9WTQptMktPNkRDK2dRK1p4OEtRd28yYnZhL0lvMTErZEFzS3BoK0VsSllKRzluWWxSMXJERzM1aCs3R0szT095c0wvCmFvcGcrc256ZDk2MFZKRlpTYVQ3UTg3aW0xekFWMk93d0FNUTJocHR6Wk1iRmlsMkdXTFRiSU16WWVJa0hOT28KZ3QxK2RwNHpiOXdLQ2hWeFlGNFdLTjc5K3dUREFyZEpmNUxiZ3ZvNHZQV3h0Ulg5cEhIMXJ1SUMveGRlenh1MQpzdkpnNzdOK0h5dmpLTmFuMTRxVUxWWnJ3OE1LMkNYb21kNEdDMmUrV09vMXlPU21nTkZFbjA4b2h5S0gzN0JsCkdNTDJMQ0pENDBWcjUraFg3TG5LSURSOXpCUm9qdTNyCj1mR2Y4Ci0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
