# This policy verifies the installation of Integrity Shield on the managed clusters.
# 
# "enforce", it will install Integirty Shield operator

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-integrity-shield
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-5 Access Restrictions for Change
    integrityshield.io/message: H4sIAEbZRmAAA+1Z3W/bNhB/919BuG9DqaQYAmx687xh60OzoM76svaBps4yF4nUSMqNV/R/75GUbNkRJadNumUoUSSNeLyP333oTnxGrtfCkEoVgm/JBrRYCTDEroEIaSwrCmaFkkStyEtpIdfCbsliLaDICD52dCWTLIeM8KI2FrRJJs8I/puCXCnNYfqcCEvei6JoOQZOQnc4VaCZVXoyYZV4gzxQZNooleCmpA1zGoSVIG0i1NnmxeRGyCwlV550UoJlGbMsnRAiWQktDypa3anxEnGfSamsN844cnKCONReZkxnJiWXLxfXZHFFfjg/pxffn3ieM9RCaQQ4JfNXZK7kSuS1Dgi/2pGeyk1Jq1XhedELMuMcjCGvwVgtuLeLoAPIfM1kDhNTAXd2ajyfCS9y5qlS0jgKNzNh2LIABHTFCuOeNPhZKCuMBGigokQt/wJuf4aVkMJz8c/durcH24PBkwegNG5tKbrubdegm6nbNRXzxoXV4tCuOB7kmQ/vIwQ8g+TOKYJJpDB9tMgykGS5DWc1cKSTOamYRlXQfrJhRQ3eM/2cko5yBlxG2m1KfhP5urMR4D92S7so4Qo3BJMcrrcV4lMi9mu2gQMyMuDFQ6dc3oGxz9sdXw557NBzd1zW1gJqthgv5dOKN5U/9UBb/0uB1nVjGwIm4UqDcr/Ks57oCh78vaH+Vau6+qII3IVe3ssqHPB5cGLcdtdxPLTLMp2D3WWY6aNxSP+/EsXUy2+Z8miZwopqzWL5sqiXhmtROe4PWbC/Ur5w7GckFCnxRvYQNF3mVcHkrKq0Qu+mZFZbVaJL+YPYZVStnVGIdlnLbukwUerLPRYu7VDIymLO6RuwGDA9r1Y8iLXBYqjOF28G9Es258mL5OJp5T/X39L/y9Mf/2+SHbYB2uC8wQqwm+QW7TB0uD6jCBjQCMwDlwBCEAZWiH/Q3thrkRfAZF0le8oeQE4uLoXKc9D9skSJ6ZGSv2u2dRhHcufsjpWOJwZcus/SI108dA8rs+EZE8lWPr4wij987NPIMwkJ36+X/1CwDZFc5RUm5u3F+Y/9JoQgm2WlkH+gXpc+gKbB5alTVHBgnKta2jRiIMXf7meWYdTfhO0Cmgc01ANudTHt10AuODLeFeAFFJhjKgK5o0cNMohtu6ibftcvihC4HT98Uy+BRjl4kv0ropfOiFyCHvKQB0XE2kknQ460nDtdBjQNeowxWDCsfbDwtDFelBjnJIyMefDv4wsd4UObWneS+lhaYdv4gxh/gAb+FDe434gbVPuqP2IRlExgJ9Pvjr30SJ0MttxPMwNch9EkdQI0VjEanvUc0BD6HIcTEl5ptRJFfJw5aA+06Zu23ML+zSI0r+soq8AOezu+HsLPEeHr0g+JJ/Q/sdKQS+yzH0abGmuf/OximA5k5UPwb4ptVIpvyOZr4Df/Fd+06+CLcIQEuaoSu4UrZpG9fGLqu+U8e6WxT7x1JSEZCgYchtT73dsvfA9OidV138zhVojymbVDRfarAsOGdQmipm3fmnS+7Sdvp6yqzNCos1bGTVk0g6pQW/cB/O10LLm+VJbpDOGPJ81sJaehLD+eEJyolORY67Gfv685BVtC4YSccN3RPHWB/xVE+Fx5JDlaKdt0rXEJR98Fx5pWnF2cAuNkJOTtL7c4Chuzv/6K24iv/lO+GAjTdG7x24LD1Y5/biAdIfUjuknJn1NXtqbvJpTSz74rdF9b3NOf8E/MxZ5bw2XYobHbw6pl8RpWnbvG9mn03K66787ju3NCOkVyJNkm3VaRjt5x9rxN7lOPj0EeqwR3Ifb29dzKjiLVDuiNIOxtM9G5q6Xu25itMSKm1y4gmvCxfiANN6nZ/OjobIP9s6vue7aH2RLLC0o++BQAuRFaSaf384Pgfd6Jzww203cfJ58AE37oP1gfAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CRzJVWWJIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leGZEd01BSTk1eEM5TXZ5Sm5zQStrNkhDYQpWSlAybEo1blUycWpnYVl3MTFjV09QRTQrVUg0QUpNT0pUNncrTmZjbkk5L3FJSGZReHpnaS9sVVhTL0l2aFluCkpLL3FZY1RaV3h6S042bCswb3Z2U2g4azZ0dUJpdkg5em9wbU5vQmc0cjYvc1dCTXVwUklYMWZxcXNiR2RyaU0KUFlMQldubnc4OFF5K0NpMlZIL1ZlTzN5TzFvaEZqUU9QYkJHSUVBYU5pTzVzbVFoTUNnWC82NkJzc3BmMFZCUgpSa01rT04raTYzSlhia1JBL0Y2dUJjTEU2RW1XY1FqTkxSVWF5cEI5Z0JMdFBEb2VZclVwTllQeVpEVnNaOEJiCloxenEyYUttZEhjeURqM2E5SjVSRWV6djFJRnRwWmNzQzhnYjhHN29tdWVJSXB1dEFNbExvdHpPL2FEWmlrRVcKRlRZRTVONXZ1Tm8rSGhPYWtpSUd2cTcvbFBiT0JaZVdHSmtOS3NaQVpROVhaSTdYZnhWUUl1akRIOUNtdjJOVApuTVpMZ2pBMENBNzE5RmxQcXIwWW0yYUFCWDRCTXk0SXdKUVVKbXNTdnlRV0VBbUFZWkxHQnRKNGFiUC9Wdm9tCmQ2ejQxSHJjSzI4N1RibG8zS1BpRzJOVGdJVytGOFhqNXpUaVkxaktwOWlUTEE9PQo9WDBwRAotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-namespace
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: High
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: integrity-shield-operator-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-og
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: integrity-operator-group
                  namespace: integrity-shield-operator-system
                spec:
                  targetNamespaces:
                    - integrity-shield-operator-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-sub
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: integrity-shield-operator
                  namespace: integrity-shield-operator-system
                spec:
                  channel: alpha
                  installPlanApproval: Automatic
                  name: integrity-shield-operator
                  source: community-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: integrity-shield-operator.v0.1.5
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-cr
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apis.integrityshield.io/v1alpha1
                kind: IntegrityShield
                metadata:
                  name: integrity-shield-server
                  namespace: integrity-shield-operator-system
                  finalizers:
                    - cleanup.finalizers.integrityshield.io
                spec:
                  logger:
                    image: quay.io/open-cluster-management/integrity-shield-logging:0.1.5
                  server:
                    image: quay.io/open-cluster-management/integrity-shield-server:0.1.5
                  affinity: {}
                  shieldConfig:
                    verifyType: pgp # x509
                    iShieldAdminUserName: "system:serviceaccount:open-cluster-management-agent-addon:klusterlet-addon-policyctrl"
                    inScopeNamespaceSelector:
                      include:
                        - "*"
                      exclude:
                        - "kube-*"
                        - "openshift-*"
                  signerConfig:
                    policies:
                      - namespaces:
                          - "*"
                        signers:
                          - "SampleSigner"
                      - scope: "Cluster"
                        signers:
                          - "SampleSigner"
                    signers:
                      - name: "SampleSigner"
                        keyConfig: sample-signer-keyconfig
                        subjects:
                          - email: "*"
                  keyConfig:
                    - name: sample-signer-keyconfig
                      secretName: keyring-secret
                  resourceSigningProfiles:
                    - name: policy-rsp
                      protectRules:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                      ignoreRules:
                        - match:
                            - username: "system:serviceaccount:open-cluster-management-agent:*"
                            - username: "system:serviceaccount:open-cluster-management-agent-addon:*"
                      forceCheckRules:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                              kind: Policy
                      kustomizePatterns:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                              kind: Policy
                          namePrefix: "*."
                          allowNamespaceChange: true
                      ignoreAttrs:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                          attrs:
                            - "metadata.annotations.\"apps.open-cluster-management.io/hosting-deployable\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/hosting-subscription\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/sync-source\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/reconcile-option\""
                            - "metadata.labels.\"policy.open-cluster-management.io/cluster-name\""
                            - "metadata.labels.\"policy.open-cluster-management.io/cluster-namespace\""
                            - "metadata.labels.\"policy.open-cluster-management.io/root-policy\""
                      targetNamespaceSelector:
                        labelSelector:
                          matchExpressions:
                            - key: policy.open-cluster-management.io/isClusterNamespace
                              operator: In
                              values: ["true"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIAEbZRmAAA+1Z3W/bNhB/919BuG9DqaQYAmx687xh60OzoM76svaBps4yF4nUSMqNV/R/75GUbNkRJadNumUoUSSNeLyP333oTnxGrtfCkEoVgm/JBrRYCTDEroEIaSwrCmaFkkStyEtpIdfCbsliLaDICD52dCWTLIeM8KI2FrRJJs8I/puCXCnNYfqcCEvei6JoOQZOQnc4VaCZVXoyYZV4gzxQZNooleCmpA1zGoSVIG0i1NnmxeRGyCwlV550UoJlGbMsnRAiWQktDypa3anxEnGfSamsN844cnKCONReZkxnJiWXLxfXZHFFfjg/pxffn3ieM9RCaQQ4JfNXZK7kSuS1Dgi/2pGeyk1Jq1XhedELMuMcjCGvwVgtuLeLoAPIfM1kDhNTAXd2ajyfCS9y5qlS0jgKNzNh2LIABHTFCuOeNPhZKCuMBGigokQt/wJuf4aVkMJz8c/durcH24PBkwegNG5tKbrubdegm6nbNRXzxoXV4tCuOB7kmQ/vIwQ8g+TOKYJJpDB9tMgykGS5DWc1cKSTOamYRlXQfrJhRQ3eM/2cko5yBlxG2m1KfhP5urMR4D92S7so4Qo3BJMcrrcV4lMi9mu2gQMyMuDFQ6dc3oGxz9sdXw557NBzd1zW1gJqthgv5dOKN5U/9UBb/0uB1nVjGwIm4UqDcr/Ks57oCh78vaH+Vau6+qII3IVe3ssqHPB5cGLcdtdxPLTLMp2D3WWY6aNxSP+/EsXUy2+Z8miZwopqzWL5sqiXhmtROe4PWbC/Ur5w7GckFCnxRvYQNF3mVcHkrKq0Qu+mZFZbVaJL+YPYZVStnVGIdlnLbukwUerLPRYu7VDIymLO6RuwGDA9r1Y8iLXBYqjOF28G9Es258mL5OJp5T/X39L/y9Mf/2+SHbYB2uC8wQqwm+QW7TB0uD6jCBjQCMwDlwBCEAZWiH/Q3thrkRfAZF0le8oeQE4uLoXKc9D9skSJ6ZGSv2u2dRhHcufsjpWOJwZcus/SI108dA8rs+EZE8lWPr4wij987NPIMwkJ36+X/1CwDZFc5RUm5u3F+Y/9JoQgm2WlkH+gXpc+gKbB5alTVHBgnKta2jRiIMXf7meWYdTfhO0Cmgc01ANudTHt10AuODLeFeAFFJhjKgK5o0cNMohtu6ibftcvihC4HT98Uy+BRjl4kv0ropfOiFyCHvKQB0XE2kknQ460nDtdBjQNeowxWDCsfbDwtDFelBjnJIyMefDv4wsd4UObWneS+lhaYdv4gxh/gAb+FDe434gbVPuqP2IRlExgJ9Pvjr30SJ0MttxPMwNch9EkdQI0VjEanvUc0BD6HIcTEl5ptRJFfJw5aA+06Zu23ML+zSI0r+soq8AOezu+HsLPEeHr0g+JJ/Q/sdKQS+yzH0abGmuf/OximA5k5UPwb4ptVIpvyOZr4Df/Fd+06+CLcIQEuaoSu4UrZpG9fGLqu+U8e6WxT7x1JSEZCgYchtT73dsvfA9OidV138zhVojymbVDRfarAsOGdQmipm3fmnS+7Sdvp6yqzNCos1bGTVk0g6pQW/cB/O10LLm+VJbpDOGPJ81sJaehLD+eEJyolORY67Gfv685BVtC4YSccN3RPHWB/xVE+Fx5JDlaKdt0rXEJR98Fx5pWnF2cAuNkJOTtL7c4Chuzv/6K24iv/lO+GAjTdG7x24LD1Y5/biAdIfUjuknJn1NXtqbvJpTSz74rdF9b3NOf8E/MxZ5bw2XYobHbw6pl8RpWnbvG9mn03K66787ju3NCOkVyJNkm3VaRjt5x9rxN7lOPj0EeqwR3Ifb29dzKjiLVDuiNIOxtM9G5q6Xu25itMSKm1y4gmvCxfiANN6nZ/OjobIP9s6vue7aH2RLLC0o++BQAuRFaSaf384Pgfd6Jzww203cfJ58AE37oP1gfAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CRzJVWWJIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leGZEd01BSTk1eEM5TXZ5Sm5zQStrNkhDYQpWSlAybEo1blUycWpnYVl3MTFjV09QRTQrVUg0QUpNT0pUNncrTmZjbkk5L3FJSGZReHpnaS9sVVhTL0l2aFluCkpLL3FZY1RaV3h6S042bCswb3Z2U2g4azZ0dUJpdkg5em9wbU5vQmc0cjYvc1dCTXVwUklYMWZxcXNiR2RyaU0KUFlMQldubnc4OFF5K0NpMlZIL1ZlTzN5TzFvaEZqUU9QYkJHSUVBYU5pTzVzbVFoTUNnWC82NkJzc3BmMFZCUgpSa01rT04raTYzSlhia1JBL0Y2dUJjTEU2RW1XY1FqTkxSVWF5cEI5Z0JMdFBEb2VZclVwTllQeVpEVnNaOEJiCloxenEyYUttZEhjeURqM2E5SjVSRWV6djFJRnRwWmNzQzhnYjhHN29tdWVJSXB1dEFNbExvdHpPL2FEWmlrRVcKRlRZRTVONXZ1Tm8rSGhPYWtpSUd2cTcvbFBiT0JaZVdHSmtOS3NaQVpROVhaSTdYZnhWUUl1akRIOUNtdjJOVApuTVpMZ2pBMENBNzE5RmxQcXIwWW0yYUFCWDRCTXk0SXdKUVVKbXNTdnlRV0VBbUFZWkxHQnRKNGFiUC9Wdm9tCmQ2ejQxSHJjSzI4N1RibG8zS1BpRzJOVGdJVytGOFhqNXpUaVkxaktwOWlUTEE9PQo9WDBwRAotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
placementRef:
  name: placement-policy-integrity-shield
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-integrity-shield
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIAEbZRmAAA+1Z3W/bNhB/919BuG9DqaQYAmx687xh60OzoM76svaBps4yF4nUSMqNV/R/75GUbNkRJadNumUoUSSNeLyP333oTnxGrtfCkEoVgm/JBrRYCTDEroEIaSwrCmaFkkStyEtpIdfCbsliLaDICD52dCWTLIeM8KI2FrRJJs8I/puCXCnNYfqcCEvei6JoOQZOQnc4VaCZVXoyYZV4gzxQZNooleCmpA1zGoSVIG0i1NnmxeRGyCwlV550UoJlGbMsnRAiWQktDypa3anxEnGfSamsN844cnKCONReZkxnJiWXLxfXZHFFfjg/pxffn3ieM9RCaQQ4JfNXZK7kSuS1Dgi/2pGeyk1Jq1XhedELMuMcjCGvwVgtuLeLoAPIfM1kDhNTAXd2ajyfCS9y5qlS0jgKNzNh2LIABHTFCuOeNPhZKCuMBGigokQt/wJuf4aVkMJz8c/durcH24PBkwegNG5tKbrubdegm6nbNRXzxoXV4tCuOB7kmQ/vIwQ8g+TOKYJJpDB9tMgykGS5DWc1cKSTOamYRlXQfrJhRQ3eM/2cko5yBlxG2m1KfhP5urMR4D92S7so4Qo3BJMcrrcV4lMi9mu2gQMyMuDFQ6dc3oGxz9sdXw557NBzd1zW1gJqthgv5dOKN5U/9UBb/0uB1nVjGwIm4UqDcr/Ks57oCh78vaH+Vau6+qII3IVe3ssqHPB5cGLcdtdxPLTLMp2D3WWY6aNxSP+/EsXUy2+Z8miZwopqzWL5sqiXhmtROe4PWbC/Ur5w7GckFCnxRvYQNF3mVcHkrKq0Qu+mZFZbVaJL+YPYZVStnVGIdlnLbukwUerLPRYu7VDIymLO6RuwGDA9r1Y8iLXBYqjOF28G9Es258mL5OJp5T/X39L/y9Mf/2+SHbYB2uC8wQqwm+QW7TB0uD6jCBjQCMwDlwBCEAZWiH/Q3thrkRfAZF0le8oeQE4uLoXKc9D9skSJ6ZGSv2u2dRhHcufsjpWOJwZcus/SI108dA8rs+EZE8lWPr4wij987NPIMwkJ36+X/1CwDZFc5RUm5u3F+Y/9JoQgm2WlkH+gXpc+gKbB5alTVHBgnKta2jRiIMXf7meWYdTfhO0Cmgc01ANudTHt10AuODLeFeAFFJhjKgK5o0cNMohtu6ibftcvihC4HT98Uy+BRjl4kv0ropfOiFyCHvKQB0XE2kknQ460nDtdBjQNeowxWDCsfbDwtDFelBjnJIyMefDv4wsd4UObWneS+lhaYdv4gxh/gAb+FDe434gbVPuqP2IRlExgJ9Pvjr30SJ0MttxPMwNch9EkdQI0VjEanvUc0BD6HIcTEl5ptRJFfJw5aA+06Zu23ML+zSI0r+soq8AOezu+HsLPEeHr0g+JJ/Q/sdKQS+yzH0abGmuf/OximA5k5UPwb4ptVIpvyOZr4Df/Fd+06+CLcIQEuaoSu4UrZpG9fGLqu+U8e6WxT7x1JSEZCgYchtT73dsvfA9OidV138zhVojymbVDRfarAsOGdQmipm3fmnS+7Sdvp6yqzNCos1bGTVk0g6pQW/cB/O10LLm+VJbpDOGPJ81sJaehLD+eEJyolORY67Gfv685BVtC4YSccN3RPHWB/xVE+Fx5JDlaKdt0rXEJR98Fx5pWnF2cAuNkJOTtL7c4Chuzv/6K24iv/lO+GAjTdG7x24LD1Y5/biAdIfUjuknJn1NXtqbvJpTSz74rdF9b3NOf8E/MxZ5bw2XYobHbw6pl8RpWnbvG9mn03K66787ju3NCOkVyJNkm3VaRjt5x9rxN7lOPj0EeqwR3Ifb29dzKjiLVDuiNIOxtM9G5q6Xu25itMSKm1y4gmvCxfiANN6nZ/OjobIP9s6vue7aH2RLLC0o++BQAuRFaSaf384Pgfd6Jzww203cfJ58AE37oP1gfAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CRzJVWWJIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leGZEd01BSTk1eEM5TXZ5Sm5zQStrNkhDYQpWSlAybEo1blUycWpnYVl3MTFjV09QRTQrVUg0QUpNT0pUNncrTmZjbkk5L3FJSGZReHpnaS9sVVhTL0l2aFluCkpLL3FZY1RaV3h6S042bCswb3Z2U2g4azZ0dUJpdkg5em9wbU5vQmc0cjYvc1dCTXVwUklYMWZxcXNiR2RyaU0KUFlMQldubnc4OFF5K0NpMlZIL1ZlTzN5TzFvaEZqUU9QYkJHSUVBYU5pTzVzbVFoTUNnWC82NkJzc3BmMFZCUgpSa01rT04raTYzSlhia1JBL0Y2dUJjTEU2RW1XY1FqTkxSVWF5cEI5Z0JMdFBEb2VZclVwTllQeVpEVnNaOEJiCloxenEyYUttZEhjeURqM2E5SjVSRWV6djFJRnRwWmNzQzhnYjhHN29tdWVJSXB1dEFNbExvdHpPL2FEWmlrRVcKRlRZRTVONXZ1Tm8rSGhPYWtpSUd2cTcvbFBiT0JaZVdHSmtOS3NaQVpROVhaSTdYZnhWUUl1akRIOUNtdjJOVApuTVpMZ2pBMENBNzE5RmxQcXIwWW0yYUFCWDRCTXk0SXdKUVVKbXNTdnlRV0VBbUFZWkxHQnRKNGFiUC9Wdm9tCmQ2ejQxSHJjSzI4N1RibG8zS1BpRzJOVGdJVytGOFhqNXpUaVkxaktwOWlUTEE9PQo9WDBwRAotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
