# This policy looks for PolicyReport resources that contain failures.
# These failures mean a compliance action was taken and there are resources that 
# do not meet the compliance rules.
#
# Set remediationAction to "inform" to receive a list of PolicyReport 
# resources that have a status of "fail".

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-check-reports
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    integrityshield.io/message: H4sIAAAAAAAAA9VVTW/bMAy9+1cQ7m2osnbDgMK3NhuGHjoMbbFL0QNjM4kWWTIkOWkw7L+Pku3UTrI0K3apgACO+PFIPlI8gfu5dFAZJfM1KGMWDqbGwvd4cUuVsR4sOVPbnBz4OXrIjfYoNUxRqpplo+SEvZCjzQ2UhBqQNctKSdQ5AeZeGg0rZCe4IJbqgt2RZRH/tiDYY2FAG8+eyAe9vi9bq4jKWncUwiupkBj8XzYo3kAqNedRpuHbUk5yyUCgpPNgpsP02M0W/ByjtvPoaxf005BZOkoSrOQPso5BsrZoI1ORFrmqnScrStQ443i0H0nzfnmeLKQushYvKcljgR6zBEBjSZ0Pkc8pXwgb43EsRM25x4xc0IUjsDhYXaAtXAbfru/u4eLsTHz6eKRxjp5mxkpi6/ENjI2eylltYwRws1E91hs3iDUq+hIf4AodKalp6DZxFeUhuR36Mmi4Y1khHU4UcQWnqBwlHbrwxN3AQbflEWAmPyn3n2kqtYxO4n04/0xZZ9hQNwi65bHT6PPZnYO8NqfLvDt/rQCcwEoqBRMCsyRrZVHw5EzWe1qe57HiQdK+he65d8S20q8znu/VVqSuwpzuSHHtjO3HBEBPXKGCc3lIF/WExLv0cSCXeiMfihoqtinqjuhN8v26YvuSeeB2D0M30IQDpO4jdzVrUl9cuIZJVNUcz3ds+iPZPAE7Kvwe1Mq7XbwQf/MsZPG1ewPd1yG9uguPaKW3Qfm4qcR/Yl4I8ep1oHjqwu0V/5V6tmcxTBqJ2PuQVJ39LU17u6S73W+0afyNMa/RJNbzqzV1lfFX5Q7En7g6khOLI1566AaLr+WtxXmxUju1fSGyPZWNye3Zt4dr1M1Ei8LTV8jeFn7ugPTe1pS2TeJjTzdrshhvmV4uuVnCEnt2O3xvS/T5/MtTxZ3nnqEC2K8F8aSRXkprdAj6FLgG/BawKVzrU1iiqsPKfkgLWqaPv5M/dQ3S2c8JAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CSzJUZ1JIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9kdkx3d0FzRXgySGpFc05IS3Z3MndNbERoM3UySUtVZ0h2V0cvQwo1Qlh3SHRPeU1sZW5hS2JtWVBFYkpadXJVUGhQSmVKUzErYVRGNitFSGFHWVgwelZZTm5PcjhpOVh4RmRlSUxCCjB6Z1hjdnJlcS9Oc0lacHRZSlVxckxVek5nM3FKeUhaSzh5MDNJOUw3K2c5QkFRRUJycmJORGRJRDdLTDJ5Sk8KaEN3bkIvTUh3aFhVYTR0T2VjeVZaODJkYXpzajF6T0c5c3FIc2ovdVh4RGUrdmJ5amY2Nm5mRk9VU2daM3NBeAplRmRtREc4d0g2Y2tDUXVhL2Flc2xqRTd6UkNwbmxmaDZLZi9qb3dqN3hPS1FFRjlTbWZtWk42SFZCOGR1djFWCitzRTV6TUlCSmJoK2VlVXplSkx0NTR3dHhwMHdGZmN0d1EwR0dpdDc5TXpWcnFjcmtMeGxWZURBTEk3V09EYXQKMUY0NWFjdlhKV2dKZ2tIWlpLajZPSTVLcGtUYVdyUTFKWFdvSTF1NHE2SXRmTWFFOTZ2NUtlMERWTnNpNTNnbgpJOVZpQzB5azNPdU4xWlM1NzFXditwMHVLQi85VFdiaXNZdnRWaDFjQXpwa2g4ckg4SWl4NVVMbHFHdHZSblI0Cjk2Sy9sWTl3ZXpwYk0yTW1sS25UR3h0NUhnWHJwZHBiCj1QemFtCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-check-reports
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["*"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: wgpolicyk8s.io/v1alpha1
                kind: PolicyReport
                results:
                  - status: fail
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-check-cluster-reports
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: wgpolicyk8s.io/v1alpha1
                kind: ClusterPolicyReport
                results:
                  - status: fail
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-check-reports
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA9VVTW/bMAy9+1cQ7m2osnbDgMK3NhuGHjoMbbFL0QNjM4kWWTIkOWkw7L+Pku3UTrI0K3apgACO+PFIPlI8gfu5dFAZJfM1KGMWDqbGwvd4cUuVsR4sOVPbnBz4OXrIjfYoNUxRqpplo+SEvZCjzQ2UhBqQNctKSdQ5AeZeGg0rZCe4IJbqgt2RZRH/tiDYY2FAG8+eyAe9vi9bq4jKWncUwiupkBj8XzYo3kAqNedRpuHbUk5yyUCgpPNgpsP02M0W/ByjtvPoaxf005BZOkoSrOQPso5BsrZoI1ORFrmqnScrStQ443i0H0nzfnmeLKQushYvKcljgR6zBEBjSZ0Pkc8pXwgb43EsRM25x4xc0IUjsDhYXaAtXAbfru/u4eLsTHz6eKRxjp5mxkpi6/ENjI2eylltYwRws1E91hs3iDUq+hIf4AodKalp6DZxFeUhuR36Mmi4Y1khHU4UcQWnqBwlHbrwxN3AQbflEWAmPyn3n2kqtYxO4n04/0xZZ9hQNwi65bHT6PPZnYO8NqfLvDt/rQCcwEoqBRMCsyRrZVHw5EzWe1qe57HiQdK+he65d8S20q8znu/VVqSuwpzuSHHtjO3HBEBPXKGCc3lIF/WExLv0cSCXeiMfihoqtinqjuhN8v26YvuSeeB2D0M30IQDpO4jdzVrUl9cuIZJVNUcz3ds+iPZPAE7Kvwe1Mq7XbwQf/MsZPG1ewPd1yG9uguPaKW3Qfm4qcR/Yl4I8ep1oHjqwu0V/5V6tmcxTBqJ2PuQVJ39LU17u6S73W+0afyNMa/RJNbzqzV1lfFX5Q7En7g6khOLI1566AaLr+WtxXmxUju1fSGyPZWNye3Zt4dr1M1Ei8LTV8jeFn7ugPTe1pS2TeJjTzdrshhvmV4uuVnCEnt2O3xvS/T5/MtTxZ3nnqEC2K8F8aSRXkprdAj6FLgG/BawKVzrU1iiqsPKfkgLWqaPv5M/dQ3S2c8JAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CSzJUZ1JIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9kdkx3d0FzRXgySGpFc05IS3Z3MndNbERoM3UySUtVZ0h2V0cvQwo1Qlh3SHRPeU1sZW5hS2JtWVBFYkpadXJVUGhQSmVKUzErYVRGNitFSGFHWVgwelZZTm5PcjhpOVh4RmRlSUxCCjB6Z1hjdnJlcS9Oc0lacHRZSlVxckxVek5nM3FKeUhaSzh5MDNJOUw3K2c5QkFRRUJycmJORGRJRDdLTDJ5Sk8KaEN3bkIvTUh3aFhVYTR0T2VjeVZaODJkYXpzajF6T0c5c3FIc2ovdVh4RGUrdmJ5amY2Nm5mRk9VU2daM3NBeAplRmRtREc4d0g2Y2tDUXVhL2Flc2xqRTd6UkNwbmxmaDZLZi9qb3dqN3hPS1FFRjlTbWZtWk42SFZCOGR1djFWCitzRTV6TUlCSmJoK2VlVXplSkx0NTR3dHhwMHdGZmN0d1EwR0dpdDc5TXpWcnFjcmtMeGxWZURBTEk3V09EYXQKMUY0NWFjdlhKV2dKZ2tIWlpLajZPSTVLcGtUYVdyUTFKWFdvSTF1NHE2SXRmTWFFOTZ2NUtlMERWTnNpNTNnbgpJOVZpQzB5azNPdU4xWlM1NzFXditwMHVLQi85VFdiaXNZdnRWaDFjQXpwa2g4ckg4SWl4NVVMbHFHdHZSblI0Cjk2Sy9sWTl3ZXpwYk0yTW1sS25UR3h0NUhnWHJwZHBiCj1QemFtCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
placementRef:
  name: placement-policy-check-reports
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-check-reports
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-check-reports
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA9VVTW/bMAy9+1cQ7m2osnbDgMK3NhuGHjoMbbFL0QNjM4kWWTIkOWkw7L+Pku3UTrI0K3apgACO+PFIPlI8gfu5dFAZJfM1KGMWDqbGwvd4cUuVsR4sOVPbnBz4OXrIjfYoNUxRqpplo+SEvZCjzQ2UhBqQNctKSdQ5AeZeGg0rZCe4IJbqgt2RZRH/tiDYY2FAG8+eyAe9vi9bq4jKWncUwiupkBj8XzYo3kAqNedRpuHbUk5yyUCgpPNgpsP02M0W/ByjtvPoaxf005BZOkoSrOQPso5BsrZoI1ORFrmqnScrStQ443i0H0nzfnmeLKQushYvKcljgR6zBEBjSZ0Pkc8pXwgb43EsRM25x4xc0IUjsDhYXaAtXAbfru/u4eLsTHz6eKRxjp5mxkpi6/ENjI2eylltYwRws1E91hs3iDUq+hIf4AodKalp6DZxFeUhuR36Mmi4Y1khHU4UcQWnqBwlHbrwxN3AQbflEWAmPyn3n2kqtYxO4n04/0xZZ9hQNwi65bHT6PPZnYO8NqfLvDt/rQCcwEoqBRMCsyRrZVHw5EzWe1qe57HiQdK+he65d8S20q8znu/VVqSuwpzuSHHtjO3HBEBPXKGCc3lIF/WExLv0cSCXeiMfihoqtinqjuhN8v26YvuSeeB2D0M30IQDpO4jdzVrUl9cuIZJVNUcz3ds+iPZPAE7Kvwe1Mq7XbwQf/MsZPG1ewPd1yG9uguPaKW3Qfm4qcR/Yl4I8ep1oHjqwu0V/5V6tmcxTBqJ2PuQVJ39LU17u6S73W+0afyNMa/RJNbzqzV1lfFX5Q7En7g6khOLI1566AaLr+WtxXmxUju1fSGyPZWNye3Zt4dr1M1Ei8LTV8jeFn7ugPTe1pS2TeJjTzdrshhvmV4uuVnCEnt2O3xvS/T5/MtTxZ3nnqEC2K8F8aSRXkprdAj6FLgG/BawKVzrU1iiqsPKfkgLWqaPv5M/dQ3S2c8JAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CSzJUZ1JIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9kdkx3d0FzRXgySGpFc05IS3Z3MndNbERoM3UySUtVZ0h2V0cvQwo1Qlh3SHRPeU1sZW5hS2JtWVBFYkpadXJVUGhQSmVKUzErYVRGNitFSGFHWVgwelZZTm5PcjhpOVh4RmRlSUxCCjB6Z1hjdnJlcS9Oc0lacHRZSlVxckxVek5nM3FKeUhaSzh5MDNJOUw3K2c5QkFRRUJycmJORGRJRDdLTDJ5Sk8KaEN3bkIvTUh3aFhVYTR0T2VjeVZaODJkYXpzajF6T0c5c3FIc2ovdVh4RGUrdmJ5amY2Nm5mRk9VU2daM3NBeAplRmRtREc4d0g2Y2tDUXVhL2Flc2xqRTd6UkNwbmxmaDZLZi9qb3dqN3hPS1FFRjlTbWZtWk42SFZCOGR1djFWCitzRTV6TUlCSmJoK2VlVXplSkx0NTR3dHhwMHdGZmN0d1EwR0dpdDc5TXpWcnFjcmtMeGxWZURBTEk3V09EYXQKMUY0NWFjdlhKV2dKZ2tIWlpLajZPSTVLcGtUYVdyUTFKWFdvSTF1NHE2SXRmTWFFOTZ2NUtlMERWTnNpNTNnbgpJOVZpQzB5azNPdU4xWlM1NzFXditwMHVLQi85VFdiaXNZdnRWaDFjQXpwa2g4ckg4SWl4NVVMbHFHdHZSblI0Cjk2Sy9sWTl3ZXpwYk0yTW1sS25UR3h0NUhnWHJwZHBiCj1QemFtCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
