# This policy verifies the installation of Integrity Shield on the managed clusters.
# 
# "enforce", it will install Integirty Shield operator

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-integrity-shield
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-5 Access Restrictions for Change
    integrityshield.io/message: H4sIAAAAAAAAA+1aS3PbNhC+61dglFsnYJzpuNPy5qidNoe4nsjNpckBAlcUagpgAVAxm8l/7wIgZcoGKPmV1J1gMnYMLHYX+/iwAPiMnK+EIbWqBG/JBrRYCjDEroAIaSyrKmaFkkQtyWtpodTCtmS+ElAVBLsd3ZpJVkJBeNUYC9pkk2cE/01BLpXmMH1OhCUfRVX1HAMnoQecatDMKj2ZsFq8Qx4oMu+UynBQ0o45DcLWIG0m1IvNy8mFkEVOzjzpZA2WFcyyfEKIZGvoeVDR606Nl4jjTEpl/eKMIycHiEPtZcF0YXJy+np+TuZn5MejI3r8/YHzOUMtlEYD52T2hsyUXIqy0cHCb7akh3JT0mpVeV70mJxwDsaQt2CsFtyvi6ADyGzFZAkTUwN369Q4vxBe5ImnyknnKBwshGGLCtCgS1YZ19PZz8K6xkiAzlSUqMVfwO3PsBRSeC6+37Vbe7CfGDy5Y5TOrT3F0L19G3UzdaOmZn5xofV26FvaHuSZD+9rFvAMshuzCCaRwvTRoihAkkUb5mrgSCdLUjONquD6yYZVDXjPxDllA+UMuIy0bU5+E+VqMBDMf90tfaOEKxwQTHI4b2u0zxptv2Ib2CEjI17cdcrpDTPGvD3w5ZjHdj13w2U9FlDTYrysn1a8qfKpB9rqKwXa0I19CJiMKw3K/Vq/iERX8ODvHfWvWjX1vSJwG3pllFWY4PPgwLgdtuvx0DfLdAl2m2EmRuMs/f9KFNwKteF3SJanFrSsqlcsFboztFmlyrlqdARb7wOePHAej2Hnfpy4tOh7fQEWrRVRIxW4WCzghPbUa3KjOOyzMjJRrDHOcvJ3w1oXaYkgfJFeHNoOLvOj7GX2Q4R93SwqYVagUatXbyIExps7uL7UNY+QNDUaHuZWu4qtjaekxhoWa60Wc6GKUxDvII1AnJOXx08sQ02z+LaXfR1YmDcLw7WoHfeHRIUvtKNxPHFIwJj3i4wBQDgHnlVMntS1Vj5BThqr1ujSWDrefl0hx++GkGHu6W1xEifiXm4xcGfzdyOSs80Vcj0ZNOD6GxjcHwzw/ybb2jaYNjhvFA+2m+u8v7zYbXeABIPbEjw0IBCCZmCV+AfXmypjeQVMNnV2RRkxyMFQgwlc4kYflXXXMsPxxIBL1hfBdA8rs+OZEsmWPr4wij99jmnkmYSEj+vlL/baEMl1WWNiXh4f/RRfQgiyk2It5B+oV6jvpsHluVNUcGCcq0baPLFAir/dz6LAqL8IwxV0HTTgAbe6msY1kHOOjLcAPIcKc0wlTO7oUYMCUsMu6qbfxUURApf7J180C6BJDp7kaouI0hlRStBjHvJGEanjn5Mh9xwRt7qMaBr02MdgzhD7YO5pU7woMc5JGBmz4N/HF7qHD+2w7iD1EVqh7fxBjJ9AA3+KA9wPpBfUeNTfsyJYM4F1TdwdV9ITOBnWcjvNDHAdrhJyJ0AjitHQF5mgIdQ5zk5IeKbVUlTp64ed8kCb2O2Ia1jNWTTN2ybJKrDDSo+vxuzniHC79Jc6B9Q/KWgoJVbdD6NNg9gn7wyG+UhWPgT/DmyTUnxBNlsBv/iv+KZvOy84CRLkqtZYLZwxi+zlE1PfNefZM4114qWDhGwsGPBopD5ud7/wfpMTq5vYmcO1EOUn1o6B7Bc1DBvXJYia9nVrNniLy95PWV2bsaPOShl3yqIF1JVq3YPV++m+5LqvLDM4kj+eNNNKTgMsP54QPFEpyRHrsZ6/7XIqtoDKCTngebLrdYH/BUT4XHkkOVop21WtaQnX7vH3Fa14dnEK7CcjIW9/ucSjsDFXz9XpNeLWf8iNgTBd5ZZ+3dtt/fHPHUj3kPojusnJn1MHW9MPE0rpnd/23W2L632Ff2IuRl75F2GEpl77657FW1gOvg3oe5Pztui+nY9754QMQHJPsk2GpSLd+01CZDe5DR5fN/I+JLhpYr++yFcUey3VH9A7QVjbFmLwbQV1d2O2wYiYnruA6MLH+gNp+PKhmF2berLB+tmh+xXb3WxJ5QUln3wKgNwIraTT+/lO8D4fxGcBm+mHz5N/AT8QMhoIIwAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CTzZCc1JIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9mMGx3d0FycEhTdmhEa1lVa0dnZm9zclYzeUxEK3cydk5pWHQrcgoyWE1SZm9wS2dYdUtDRVYxN0doZHVoWlBCMkg2MndpZjI5aXdhQ1VGSE5NeHhmck5iUEN1RWw1RXhEZXd4aW01CnU3V1BhRSs1ZnJGZlFsOXJqK0JnUWxYc1h3WGJCbkhYQWRIZlE2YUh1emlrdU9BeUZsR0tEUGs4ZzlyRlJXVWQKU3NyWGtGU3Rpb1VhMTBmSWlCOHpoc1MvQnlWbGpzVklGbTRmMW9yOWs5MTlreWF6aU1DVDZ3M2szZWRmVm50bQpIQWQzNk1KZHorR0tLNllPUkVXcmNtRmFlL0dSZGJ4cGxMUWxRU2tTcU16Y1R4WEQxWU9YNTVpVnBzT2hrdnVyCnFPU1ljV2ZBM0dBVGhrS2RvMG0yNG9xaVlIK2NpcXBzbkdjakJldzN3VkZHS2JoanQxMndiU29pSyt2WmVjWHUKNzJXbjVuUFZNM2l1VTZuNWZrcmtTZzRzbHAvTUpXVmNYby9WNmNNUHRjNlNQUUEvQkl6ZzdDczUwUGRRaDdBWApjWmFVZ3ZqdU9KOXdGUEd6ZzFNMlNFVzFwOVV2Skw0VkxidkJMNU1HbzEwUTk2NkJUVmhUWUthNnhQNVNhQmg4CkUrRE1SWmhLOHI1ZXdoZmwvVXBjRyt3RnZKc1ltd3JnCj16dVJnCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-namespace
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: High
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: integrity-shield-operator-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-og
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: integrity-operator-group
                  namespace: integrity-shield-operator-system
                spec:
                  targetNamespaces:
                    - integrity-shield-operator-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-catrsc
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: integrity-shield-operator-catalog
                  namespace: openshift-marketplace
                spec:
                  displayName: Integrity Shield Operator
                  image: quay.io/open-cluster-management/integrity-shield-operator-index:0.1.6
                  publisher: IBM
                  sourceType: grpc
                  updateStrategy:
                    registryPoll:
                      interval: 15m
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-sub
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: integrity-shield-operator
                  namespace: integrity-shield-operator-system
                spec:
                  channel: alpha
                  installPlanApproval: Automatic
                  name: integrity-shield-operator
                  source: integrity-shield-operator-catalog
                  sourceNamespace: openshift-marketplace
                  startingCSV: integrity-shield-operator.v0.1.6
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-cr
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apis.integrityshield.io/v1alpha1
                kind: IntegrityShield
                metadata:
                  name: integrity-shield-server
                  namespace: integrity-shield-operator-system
                  finalizers:
                    - cleanup.finalizers.integrityshield.io
                spec:
                  logger:
                    image: quay.io/open-cluster-management/integrity-shield-logging:0.1.6
                  server:
                    image: quay.io/open-cluster-management/integrity-shield-server:0.1.6
                  affinity: {}
                  shieldConfig:
                    verifyType: pgp # x509
                    iShieldAdminUserName: "system:serviceaccount:open-cluster-management-agent-addon:klusterlet-addon-policyctrl"
                    inScopeNamespaceSelector:
                      include:
                        - "*"
                      exclude:
                        - "kube-*"
                        - "openshift-*"
                  signerConfig:
                    policies:
                      - namespaces:
                          - "*"
                        signers:
                          - "SampleSigner"
                      - scope: "Cluster"
                        signers:
                          - "SampleSigner"
                    signers:
                      - name: "SampleSigner"
                        keyConfig: sample-signer-keyconfig
                        subjects:
                          - email: "*"
                  keyConfig:
                    - name: sample-signer-keyconfig
                      secretName: keyring-secret
                  resourceSigningProfiles:
                    - name: policy-rsp
                      protectRules:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                      ignoreRules:
                        - match:
                            - username: "system:serviceaccount:open-cluster-management-agent:*"
                            - username: "system:serviceaccount:open-cluster-management-agent-addon:*"
                      forceCheckRules:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                              kind: Policy
                      kustomizePatterns:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                              kind: Policy
                          namePrefix: "*."
                          allowNamespaceChange: true
                      ignoreAttrs:
                        - match:
                            - apiGroup: policy.open-cluster-management.io
                          attrs:
                            - "metadata.annotations.\"apps.open-cluster-management.io/hosting-deployable\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/hosting-subscription\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/sync-source\""
                            - "metadata.annotations.\"apps.open-cluster-management.io/reconcile-option\""
                            - "metadata.labels.\"policy.open-cluster-management.io/cluster-name\""
                            - "metadata.labels.\"policy.open-cluster-management.io/cluster-namespace\""
                            - "metadata.labels.\"policy.open-cluster-management.io/root-policy\""
                      targetNamespaceSelector:
                        labelSelector:
                          matchExpressions:
                            - key: policy.open-cluster-management.io/isClusterNamespace
                              operator: In
                              values: ["true"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA+1aS3PbNhC+61dglFsnYJzpuNPy5qidNoe4nsjNpckBAlcUagpgAVAxm8l/7wIgZcoGKPmV1J1gMnYMLHYX+/iwAPiMnK+EIbWqBG/JBrRYCjDEroAIaSyrKmaFkkQtyWtpodTCtmS+ElAVBLsd3ZpJVkJBeNUYC9pkk2cE/01BLpXmMH1OhCUfRVX1HAMnoQecatDMKj2ZsFq8Qx4oMu+UynBQ0o45DcLWIG0m1IvNy8mFkEVOzjzpZA2WFcyyfEKIZGvoeVDR606Nl4jjTEpl/eKMIycHiEPtZcF0YXJy+np+TuZn5MejI3r8/YHzOUMtlEYD52T2hsyUXIqy0cHCb7akh3JT0mpVeV70mJxwDsaQt2CsFtyvi6ADyGzFZAkTUwN369Q4vxBe5ImnyknnKBwshGGLCtCgS1YZ19PZz8K6xkiAzlSUqMVfwO3PsBRSeC6+37Vbe7CfGDy5Y5TOrT3F0L19G3UzdaOmZn5xofV26FvaHuSZD+9rFvAMshuzCCaRwvTRoihAkkUb5mrgSCdLUjONquD6yYZVDXjPxDllA+UMuIy0bU5+E+VqMBDMf90tfaOEKxwQTHI4b2u0zxptv2Ib2CEjI17cdcrpDTPGvD3w5ZjHdj13w2U9FlDTYrysn1a8qfKpB9rqKwXa0I19CJiMKw3K/Vq/iERX8ODvHfWvWjX1vSJwG3pllFWY4PPgwLgdtuvx0DfLdAl2m2EmRuMs/f9KFNwKteF3SJanFrSsqlcsFboztFmlyrlqdARb7wOePHAej2Hnfpy4tOh7fQEWrRVRIxW4WCzghPbUa3KjOOyzMjJRrDHOcvJ3w1oXaYkgfJFeHNoOLvOj7GX2Q4R93SwqYVagUatXbyIExps7uL7UNY+QNDUaHuZWu4qtjaekxhoWa60Wc6GKUxDvII1AnJOXx08sQ02z+LaXfR1YmDcLw7WoHfeHRIUvtKNxPHFIwJj3i4wBQDgHnlVMntS1Vj5BThqr1ujSWDrefl0hx++GkGHu6W1xEifiXm4xcGfzdyOSs80Vcj0ZNOD6GxjcHwzw/ybb2jaYNjhvFA+2m+u8v7zYbXeABIPbEjw0IBCCZmCV+AfXmypjeQVMNnV2RRkxyMFQgwlc4kYflXXXMsPxxIBL1hfBdA8rs+OZEsmWPr4wij99jmnkmYSEj+vlL/baEMl1WWNiXh4f/RRfQgiyk2It5B+oV6jvpsHluVNUcGCcq0baPLFAir/dz6LAqL8IwxV0HTTgAbe6msY1kHOOjLcAPIcKc0wlTO7oUYMCUsMu6qbfxUURApf7J180C6BJDp7kaouI0hlRStBjHvJGEanjn5Mh9xwRt7qMaBr02MdgzhD7YO5pU7woMc5JGBmz4N/HF7qHD+2w7iD1EVqh7fxBjJ9AA3+KA9wPpBfUeNTfsyJYM4F1TdwdV9ITOBnWcjvNDHAdrhJyJ0AjitHQF5mgIdQ5zk5IeKbVUlTp64ed8kCb2O2Ia1jNWTTN2ybJKrDDSo+vxuzniHC79Jc6B9Q/KWgoJVbdD6NNg9gn7wyG+UhWPgT/DmyTUnxBNlsBv/iv+KZvOy84CRLkqtZYLZwxi+zlE1PfNefZM4114qWDhGwsGPBopD5ud7/wfpMTq5vYmcO1EOUn1o6B7Bc1DBvXJYia9nVrNniLy95PWV2bsaPOShl3yqIF1JVq3YPV++m+5LqvLDM4kj+eNNNKTgMsP54QPFEpyRHrsZ6/7XIqtoDKCTngebLrdYH/BUT4XHkkOVop21WtaQnX7vH3Fa14dnEK7CcjIW9/ucSjsDFXz9XpNeLWf8iNgTBd5ZZ+3dtt/fHPHUj3kPojusnJn1MHW9MPE0rpnd/23W2L632Ff2IuRl75F2GEpl77657FW1gOvg3oe5Pztui+nY9754QMQHJPsk2GpSLd+01CZDe5DR5fN/I+JLhpYr++yFcUey3VH9A7QVjbFmLwbQV1d2O2wYiYnruA6MLH+gNp+PKhmF2berLB+tmh+xXb3WxJ5QUln3wKgNwIraTT+/lO8D4fxGcBm+mHz5N/AT8QMhoIIwAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CTzZCc1JIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9mMGx3d0FycEhTdmhEa1lVa0dnZm9zclYzeUxEK3cydk5pWHQrcgoyWE1SZm9wS2dYdUtDRVYxN0doZHVoWlBCMkg2MndpZjI5aXdhQ1VGSE5NeHhmck5iUEN1RWw1RXhEZXd4aW01CnU3V1BhRSs1ZnJGZlFsOXJqK0JnUWxYc1h3WGJCbkhYQWRIZlE2YUh1emlrdU9BeUZsR0tEUGs4ZzlyRlJXVWQKU3NyWGtGU3Rpb1VhMTBmSWlCOHpoc1MvQnlWbGpzVklGbTRmMW9yOWs5MTlreWF6aU1DVDZ3M2szZWRmVm50bQpIQWQzNk1KZHorR0tLNllPUkVXcmNtRmFlL0dSZGJ4cGxMUWxRU2tTcU16Y1R4WEQxWU9YNTVpVnBzT2hrdnVyCnFPU1ljV2ZBM0dBVGhrS2RvMG0yNG9xaVlIK2NpcXBzbkdjakJldzN3VkZHS2JoanQxMndiU29pSyt2WmVjWHUKNzJXbjVuUFZNM2l1VTZuNWZrcmtTZzRzbHAvTUpXVmNYby9WNmNNUHRjNlNQUUEvQkl6ZzdDczUwUGRRaDdBWApjWmFVZ3ZqdU9KOXdGUEd6ZzFNMlNFVzFwOVV2Skw0VkxidkJMNU1HbzEwUTk2NkJUVmhUWUthNnhQNVNhQmg4CkUrRE1SWmhLOHI1ZXdoZmwvVXBjRyt3RnZKc1ltd3JnCj16dVJnCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
placementRef:
  name: placement-policy-integrity-shield
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-integrity-shield
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-integrity-shield
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA+1aS3PbNhC+61dglFsnYJzpuNPy5qidNoe4nsjNpckBAlcUagpgAVAxm8l/7wIgZcoGKPmV1J1gMnYMLHYX+/iwAPiMnK+EIbWqBG/JBrRYCjDEroAIaSyrKmaFkkQtyWtpodTCtmS+ElAVBLsd3ZpJVkJBeNUYC9pkk2cE/01BLpXmMH1OhCUfRVX1HAMnoQecatDMKj2ZsFq8Qx4oMu+UynBQ0o45DcLWIG0m1IvNy8mFkEVOzjzpZA2WFcyyfEKIZGvoeVDR606Nl4jjTEpl/eKMIycHiEPtZcF0YXJy+np+TuZn5MejI3r8/YHzOUMtlEYD52T2hsyUXIqy0cHCb7akh3JT0mpVeV70mJxwDsaQt2CsFtyvi6ADyGzFZAkTUwN369Q4vxBe5ImnyknnKBwshGGLCtCgS1YZ19PZz8K6xkiAzlSUqMVfwO3PsBRSeC6+37Vbe7CfGDy5Y5TOrT3F0L19G3UzdaOmZn5xofV26FvaHuSZD+9rFvAMshuzCCaRwvTRoihAkkUb5mrgSCdLUjONquD6yYZVDXjPxDllA+UMuIy0bU5+E+VqMBDMf90tfaOEKxwQTHI4b2u0zxptv2Ib2CEjI17cdcrpDTPGvD3w5ZjHdj13w2U9FlDTYrysn1a8qfKpB9rqKwXa0I19CJiMKw3K/Vq/iERX8ODvHfWvWjX1vSJwG3pllFWY4PPgwLgdtuvx0DfLdAl2m2EmRuMs/f9KFNwKteF3SJanFrSsqlcsFboztFmlyrlqdARb7wOePHAej2Hnfpy4tOh7fQEWrRVRIxW4WCzghPbUa3KjOOyzMjJRrDHOcvJ3w1oXaYkgfJFeHNoOLvOj7GX2Q4R93SwqYVagUatXbyIExps7uL7UNY+QNDUaHuZWu4qtjaekxhoWa60Wc6GKUxDvII1AnJOXx08sQ02z+LaXfR1YmDcLw7WoHfeHRIUvtKNxPHFIwJj3i4wBQDgHnlVMntS1Vj5BThqr1ujSWDrefl0hx++GkGHu6W1xEifiXm4xcGfzdyOSs80Vcj0ZNOD6GxjcHwzw/ybb2jaYNjhvFA+2m+u8v7zYbXeABIPbEjw0IBCCZmCV+AfXmypjeQVMNnV2RRkxyMFQgwlc4kYflXXXMsPxxIBL1hfBdA8rs+OZEsmWPr4wij99jmnkmYSEj+vlL/baEMl1WWNiXh4f/RRfQgiyk2It5B+oV6jvpsHluVNUcGCcq0baPLFAir/dz6LAqL8IwxV0HTTgAbe6msY1kHOOjLcAPIcKc0wlTO7oUYMCUsMu6qbfxUURApf7J180C6BJDp7kaouI0hlRStBjHvJGEanjn5Mh9xwRt7qMaBr02MdgzhD7YO5pU7woMc5JGBmz4N/HF7qHD+2w7iD1EVqh7fxBjJ9AA3+KA9wPpBfUeNTfsyJYM4F1TdwdV9ITOBnWcjvNDHAdrhJyJ0AjitHQF5mgIdQ5zk5IeKbVUlTp64ed8kCb2O2Ia1jNWTTN2ybJKrDDSo+vxuzniHC79Jc6B9Q/KWgoJVbdD6NNg9gn7wyG+UhWPgT/DmyTUnxBNlsBv/iv+KZvOy84CRLkqtZYLZwxi+zlE1PfNefZM4114qWDhGwsGPBopD5ud7/wfpMTq5vYmcO1EOUn1o6B7Bc1DBvXJYia9nVrNniLy95PWV2bsaPOShl3yqIF1JVq3YPV++m+5LqvLDM4kj+eNNNKTgMsP54QPFEpyRHrsZ6/7XIqtoDKCTngebLrdYH/BUT4XHkkOVop21WtaQnX7vH3Fa14dnEK7CcjIW9/ucSjsDFXz9XpNeLWf8iNgTBd5ZZ+3dtt/fHPHUj3kPojusnJn1MHW9MPE0rpnd/23W2L632Ff2IuRl75F2GEpl77657FW1gOvg3oe5Pztui+nY9754QMQHJPsk2GpSLd+01CZDe5DR5fN/I+JLhpYr++yFcUey3VH9A7QVjbFmLwbQV1d2O2wYiYnruA6MLH+gNp+PKhmF2berLB+tmh+xXb3WxJ5QUln3wKgNwIraTT+/lO8D4fxGcBm+mHz5N/AT8QMhoIIwAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEZCQUFCQ2dBdkZpRUVkZENIUWpWblNBUmhaMytYbTBOT3crQXJsb2NGQW1CTzZCc1JIR2RoYW1GdVFHcHcKTG1saWJTNWpiMjBBQ2drUW0wTk93K0FybG9mMGx3d0FycEhTdmhEa1lVa0dnZm9zclYzeUxEK3cydk5pWHQrcgoyWE1SZm9wS2dYdUtDRVYxN0doZHVoWlBCMkg2MndpZjI5aXdhQ1VGSE5NeHhmck5iUEN1RWw1RXhEZXd4aW01CnU3V1BhRSs1ZnJGZlFsOXJqK0JnUWxYc1h3WGJCbkhYQWRIZlE2YUh1emlrdU9BeUZsR0tEUGs4ZzlyRlJXVWQKU3NyWGtGU3Rpb1VhMTBmSWlCOHpoc1MvQnlWbGpzVklGbTRmMW9yOWs5MTlreWF6aU1DVDZ3M2szZWRmVm50bQpIQWQzNk1KZHorR0tLNllPUkVXcmNtRmFlL0dSZGJ4cGxMUWxRU2tTcU16Y1R4WEQxWU9YNTVpVnBzT2hrdnVyCnFPU1ljV2ZBM0dBVGhrS2RvMG0yNG9xaVlIK2NpcXBzbkdjakJldzN3VkZHS2JoanQxMndiU29pSyt2WmVjWHUKNzJXbjVuUFZNM2l1VTZuNWZrcmtTZzRzbHAvTUpXVmNYby9WNmNNUHRjNlNQUUEvQkl6ZzdDczUwUGRRaDdBWApjWmFVZ3ZqdU9KOXdGUEd6ZzFNMlNFVzFwOVV2Skw0VkxidkJMNU1HbzEwUTk2NkJUVmhUWUthNnhQNVNhQmg4CkUrRE1SWmhLOHI1ZXdoZmwvVXBjRyt3RnZKc1ltd3JnCj16dVJnCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQo=
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
