apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-sysdig
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SI System and Information Integrity
    policy.open-cluster-management.io/controls: SI-5 Security Alerts, Advisories, and Directives
    integrityshield.io/message: H4sIALTeRmAAA+1YbWvbOhT+nl9xyL6NKtsYg2EuF7y0lDDWlbkMxmUURT5xdGNLRpK9hbH/fo8UO3USpS+7+7BC9aWpdPSct+ccyeK1/IzGSq0SqHUpxXqia1RMlI11aFjFFS+wQuUmUr9oX41WUuUJXAbRUYWO59zxZASgeIU9BrNrm8uCZrlS2nFH+NYLwT2UWMdVzk1uE7iYZVeQXcLbly/Zm9f33C+4w0IbiQSQzSBbk0xFhuQwUwttqmAN/SYpI936vqhaOaPLgMneQIai8bshLdE4ewJp3kobtJ4EXafSoHCyRTuyNQrvvCGwXAb1qXAh5OgtEkiLubR8XiLFdsFL62e6UJLxdUkudfFjoOf/EvIpLqSSASXM+8Efmsx+4yapU60WsmhMsLDLcC8xzHQ/Ihlnym4Ferf7cdx9eAZuifsOB4DJwS6QFnSLxsg8RwXz9WYvRZvkVAE1N2QXuQstLxsE0nAEaTIwziJBUj4TKPW3PR9tzQVmWFLUtRl6BIDfKbY5ReGf8aqZI3s+/rqzLtV2fXdpk8T95PaDgdC0ILkSeLWuaX9FGaRKWvIWdyThFjrEaDFI+m7yL3pHD9ZjqR+GJ4Eu98Q14o42B3KBCfDj52MgcO9EYXRTP3F5MAZc3ovVH8Hs3hg7Edqg9n+qF0fp/rGTPt9Jcz8eTPkiCjMI+T2LJALhuCnQbcvTxmR8XGP4f3it2WZuhZG1h3gqtcF4nKXGy3rJjxVcFst1P/7/EfNbSk0s6bqKJQE4fxeLSEhFS2V5WXKV1rXRxJUE0sZpf6sUd1kv6KooFxLziKDVjfG2b2W25tuj0hc3LvvStUu5cFS3ZoWOCBE5ysF7RviqmGafD+I0aV9N3k5eP4bO0eWBP3WOx9U5NjbdfjRnQSYtiD+/3Ci43826bFcxpN/SMKyITlMnMUhhTcCZJlqFQV9867MMHXBBJ72FFa6jMpvl90jsGf+VfclOZ+fX6fnZxdV1Op2eZdn1+7Mvf49HjLHRg4u1+8D3/cPPvqN/ieWRT/35ZoXtfvLX/cZPuBg8C/SzbP+BYE/dpyb0XbI63MwS+lXbWywe0R3CEzAwmB15hNhquWk2NwruDMpBGO8wKRLE4FXkseRIVHq6dfDUMHM5eEJhvou7xlLyr4hf444iLlTqh2BKPt3bmrZclt2h1sHuNhg6wMTy7Du1NWtvVHllP1aeZ6haabTy1p5sLwAJzNTJpu1Z33JybMdff47+A9NV3NFVEgAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CRzNyUWJIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leGprc0wvM0VOZkdYUkhRYzFUd0ZqSFFhSAo4YnE3SkJLSXBrNEVqbG4rWnBpd2piZTFRcm9FRFhPb2l2ZVpZVWdzQUZlcHEvL2dTNmt1S2tLcjhIR0duUjhvCllqTlF3bE00cFUraW5obFlkUzVjUkRUcnRVWkV0REpPalVJSjg4NFZraHN4TEtCSjNob1loNXBjanB5bEdwM1kKRVVqUEJiWFJEclJJN2tsNGJWR3h1VTVGTE52Q1ppZmpwRGxVUitiQ0dsTk45dGloS2U1NXp4aDhSM3BEcThITgpGbEp5QVp6ZkJ3LzF5NVlzYU1tWkRheTdoMHlNWDdwcmltcWx0azJTclF0K0pVRitlV3g1TDJ5akp6ZDVzWFRxCjRsQ1dZNmxPK2lyUXI5TUhieis1Y0RxWDMwT1BmWVA3dlRmeUh6RlVqbjM4cTYvbnJZTmJuNko0UzhLam1LTFQKTTJPRFFWOHpmMlFoZmJQV1dremthK082aWpHUFZ1YW16eUFXTnhqQ2ttK05HckVpMXpERFpIYkNXUDJ1bHoyNApmdkV5a012M2VmSG1tak0vWmZlSFBRNHpMT0RMVUJERGVtdWdiYm9EMG9sa1RmYm1rV1VVVGhodzY1MmpqZ3UyCjZ1MVhWRndvUERDa01IQ3YyeWtQWCtVZzRRcjZXQTdpTk4xU1pTRmhrckk2eVE9PQo9b2VTLwotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-sysdig-ns
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["*"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: sysdig-operator
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-sysdig-operatorgroup
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["sysdig-operator"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: sysdig-operatorgroup
                  namespace: sysdig-operator
                spec:
                  targetNamespaces:
                    - sysdig-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-sysdig-subscription
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["sysdig-operator"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: sysdig-operator
                  namespace: sysdig-operator
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: sysdig-certified
                  source: certified-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: sysdig-operator.v1.8.3
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-sysdig-installation
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["sysdig-operator"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: sysdig.com/v1
                kind: SysdigAgent
                metadata:
                  name: sysdigagent-enforcement
                  namespace: sysdig-operator
                spec:
                  scc:
                    create: true
                  sysdig:
                    #Set access key
                    accessKey: "<SYSDIG_AGENT_ACCESS_KEY>"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-sysdig
  annotations:
    integrityshield.io/message: H4sIALTeRmAAA+1YbWvbOhT+nl9xyL6NKtsYg2EuF7y0lDDWlbkMxmUURT5xdGNLRpK9hbH/fo8UO3USpS+7+7BC9aWpdPSct+ccyeK1/IzGSq0SqHUpxXqia1RMlI11aFjFFS+wQuUmUr9oX41WUuUJXAbRUYWO59zxZASgeIU9BrNrm8uCZrlS2nFH+NYLwT2UWMdVzk1uE7iYZVeQXcLbly/Zm9f33C+4w0IbiQSQzSBbk0xFhuQwUwttqmAN/SYpI936vqhaOaPLgMneQIai8bshLdE4ewJp3kobtJ4EXafSoHCyRTuyNQrvvCGwXAb1qXAh5OgtEkiLubR8XiLFdsFL62e6UJLxdUkudfFjoOf/EvIpLqSSASXM+8Efmsx+4yapU60WsmhMsLDLcC8xzHQ/Ihlnym4Ferf7cdx9eAZuifsOB4DJwS6QFnSLxsg8RwXz9WYvRZvkVAE1N2QXuQstLxsE0nAEaTIwziJBUj4TKPW3PR9tzQVmWFLUtRl6BIDfKbY5ReGf8aqZI3s+/rqzLtV2fXdpk8T95PaDgdC0ILkSeLWuaX9FGaRKWvIWdyThFjrEaDFI+m7yL3pHD9ZjqR+GJ4Eu98Q14o42B3KBCfDj52MgcO9EYXRTP3F5MAZc3ovVH8Hs3hg7Edqg9n+qF0fp/rGTPt9Jcz8eTPkiCjMI+T2LJALhuCnQbcvTxmR8XGP4f3it2WZuhZG1h3gqtcF4nKXGy3rJjxVcFst1P/7/EfNbSk0s6bqKJQE4fxeLSEhFS2V5WXKV1rXRxJUE0sZpf6sUd1kv6KooFxLziKDVjfG2b2W25tuj0hc3LvvStUu5cFS3ZoWOCBE5ysF7RviqmGafD+I0aV9N3k5eP4bO0eWBP3WOx9U5NjbdfjRnQSYtiD+/3Ci43826bFcxpN/SMKyITlMnMUhhTcCZJlqFQV9867MMHXBBJ72FFa6jMpvl90jsGf+VfclOZ+fX6fnZxdV1Op2eZdn1+7Mvf49HjLHRg4u1+8D3/cPPvqN/ieWRT/35ZoXtfvLX/cZPuBg8C/SzbP+BYE/dpyb0XbI63MwS+lXbWywe0R3CEzAwmB15hNhquWk2NwruDMpBGO8wKRLE4FXkseRIVHq6dfDUMHM5eEJhvou7xlLyr4hf444iLlTqh2BKPt3bmrZclt2h1sHuNhg6wMTy7Du1NWtvVHllP1aeZ6haabTy1p5sLwAJzNTJpu1Z33JybMdff47+A9NV3NFVEgAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CRzNyUWJIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leGprc0wvM0VOZkdYUkhRYzFUd0ZqSFFhSAo4YnE3SkJLSXBrNEVqbG4rWnBpd2piZTFRcm9FRFhPb2l2ZVpZVWdzQUZlcHEvL2dTNmt1S2tLcjhIR0duUjhvCllqTlF3bE00cFUraW5obFlkUzVjUkRUcnRVWkV0REpPalVJSjg4NFZraHN4TEtCSjNob1loNXBjanB5bEdwM1kKRVVqUEJiWFJEclJJN2tsNGJWR3h1VTVGTE52Q1ppZmpwRGxVUitiQ0dsTk45dGloS2U1NXp4aDhSM3BEcThITgpGbEp5QVp6ZkJ3LzF5NVlzYU1tWkRheTdoMHlNWDdwcmltcWx0azJTclF0K0pVRitlV3g1TDJ5akp6ZDVzWFRxCjRsQ1dZNmxPK2lyUXI5TUhieis1Y0RxWDMwT1BmWVA3dlRmeUh6RlVqbjM4cTYvbnJZTmJuNko0UzhLam1LTFQKTTJPRFFWOHpmMlFoZmJQV1dremthK082aWpHUFZ1YW16eUFXTnhqQ2ttK05HckVpMXpERFpIYkNXUDJ1bHoyNApmdkV5a012M2VmSG1tak0vWmZlSFBRNHpMT0RMVUJERGVtdWdiYm9EMG9sa1RmYm1rV1VVVGhodzY1MmpqZ3UyCjZ1MVhWRndvUERDa01IQ3YyeWtQWCtVZzRRcjZXQTdpTk4xU1pTRmhrckk2eVE9PQo9b2VTLwotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
placementRef:
  name: placement-policy-sysdig
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-sysdig
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-sysdig
  annotations:
    integrityshield.io/message: H4sIALTeRmAAA+1YbWvbOhT+nl9xyL6NKtsYg2EuF7y0lDDWlbkMxmUURT5xdGNLRpK9hbH/fo8UO3USpS+7+7BC9aWpdPSct+ccyeK1/IzGSq0SqHUpxXqia1RMlI11aFjFFS+wQuUmUr9oX41WUuUJXAbRUYWO59zxZASgeIU9BrNrm8uCZrlS2nFH+NYLwT2UWMdVzk1uE7iYZVeQXcLbly/Zm9f33C+4w0IbiQSQzSBbk0xFhuQwUwttqmAN/SYpI936vqhaOaPLgMneQIai8bshLdE4ewJp3kobtJ4EXafSoHCyRTuyNQrvvCGwXAb1qXAh5OgtEkiLubR8XiLFdsFL62e6UJLxdUkudfFjoOf/EvIpLqSSASXM+8Efmsx+4yapU60WsmhMsLDLcC8xzHQ/Ihlnym4Ferf7cdx9eAZuifsOB4DJwS6QFnSLxsg8RwXz9WYvRZvkVAE1N2QXuQstLxsE0nAEaTIwziJBUj4TKPW3PR9tzQVmWFLUtRl6BIDfKbY5ReGf8aqZI3s+/rqzLtV2fXdpk8T95PaDgdC0ILkSeLWuaX9FGaRKWvIWdyThFjrEaDFI+m7yL3pHD9ZjqR+GJ4Eu98Q14o42B3KBCfDj52MgcO9EYXRTP3F5MAZc3ovVH8Hs3hg7Edqg9n+qF0fp/rGTPt9Jcz8eTPkiCjMI+T2LJALhuCnQbcvTxmR8XGP4f3it2WZuhZG1h3gqtcF4nKXGy3rJjxVcFst1P/7/EfNbSk0s6bqKJQE4fxeLSEhFS2V5WXKV1rXRxJUE0sZpf6sUd1kv6KooFxLziKDVjfG2b2W25tuj0hc3LvvStUu5cFS3ZoWOCBE5ysF7RviqmGafD+I0aV9N3k5eP4bO0eWBP3WOx9U5NjbdfjRnQSYtiD+/3Ci43826bFcxpN/SMKyITlMnMUhhTcCZJlqFQV9867MMHXBBJ72FFa6jMpvl90jsGf+VfclOZ+fX6fnZxdV1Op2eZdn1+7Mvf49HjLHRg4u1+8D3/cPPvqN/ieWRT/35ZoXtfvLX/cZPuBg8C/SzbP+BYE/dpyb0XbI63MwS+lXbWywe0R3CEzAwmB15hNhquWk2NwruDMpBGO8wKRLE4FXkseRIVHq6dfDUMHM5eEJhvou7xlLyr4hf444iLlTqh2BKPt3bmrZclt2h1sHuNhg6wMTy7Du1NWtvVHllP1aeZ6haabTy1p5sLwAJzNTJpu1Z33JybMdff47+A9NV3NFVEgAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSFBCQUFCQ0FBNUZpRUVWSlRXK3hrWFZWcUdrSlRYZXJVUms4em81N0VGQW1CRzNyUWJIR2hwY205cmRXNXAKTG10cGRHRm9ZWEpoTVVCcFltMHVZMjl0QUFvSkVIcTFFWlBNNk9leGprc0wvM0VOZkdYUkhRYzFUd0ZqSFFhSAo4YnE3SkJLSXBrNEVqbG4rWnBpd2piZTFRcm9FRFhPb2l2ZVpZVWdzQUZlcHEvL2dTNmt1S2tLcjhIR0duUjhvCllqTlF3bE00cFUraW5obFlkUzVjUkRUcnRVWkV0REpPalVJSjg4NFZraHN4TEtCSjNob1loNXBjanB5bEdwM1kKRVVqUEJiWFJEclJJN2tsNGJWR3h1VTVGTE52Q1ppZmpwRGxVUitiQ0dsTk45dGloS2U1NXp4aDhSM3BEcThITgpGbEp5QVp6ZkJ3LzF5NVlzYU1tWkRheTdoMHlNWDdwcmltcWx0azJTclF0K0pVRitlV3g1TDJ5akp6ZDVzWFRxCjRsQ1dZNmxPK2lyUXI5TUhieis1Y0RxWDMwT1BmWVA3dlRmeUh6RlVqbjM4cTYvbnJZTmJuNko0UzhLam1LTFQKTTJPRFFWOHpmMlFoZmJQV1dremthK082aWpHUFZ1YW16eUFXTnhqQ2ttK05HckVpMXpERFpIYkNXUDJ1bHoyNApmdkV5a012M2VmSG1tak0vWmZlSFBRNHpMT0RMVUJERGVtdWdiYm9EMG9sa1RmYm1rV1VVVGhodzY1MmpqZ3UyCjZ1MVhWRndvUERDa01IQ3YyeWtQWCtVZzRRcjZXQTdpTk4xU1pTRmhrckk2eVE9PQo9b2VTLwotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0K
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
